services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ../src:/var/www/html
    networks:
        - local_network
    depends_on:
      - php
      - mysql

  php:
    container_name: php
    build:
        context: php
        dockerfile: Dockerfile
    volumes:
      - ../src:/var/www/html
    networks:
        - local_network

  composer:
    image: composer:2.5
    container_name: composer
    volumes:
      - ../src:/var/www/html
    networks:
        - local_network
    command: composer --remove-orphans

  mysql:
    image: mysql:8.4.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3316:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
        - local_network

  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    networks:
        - local_network


networks:
  local_network:
    driver: bridge
volumes:
    db_data:
        driver: local